package com.xyafu.gtms.dao;

import com.xyafu.gtms.entity.Level;

public interface LevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int insert(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int insertSelective(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    Level selectByPrimaryKey(String level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Level record);
}