package com.xyafu.gtms.dao;

import com.xyafu.gtms.entity.Power;

import java.util.ArrayList;

public interface PowerMapper {
    ArrayList selectByLevel(int funlevel);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String power);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated
     */
    int insert(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated
     */
    int insertSelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated
     */
    Power selectByPrimaryKey(String power);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Power record);
}