package com.xyafu.gtms.dao;

import com.xyafu.gtms.entity.Student_subject;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface Student_subjectMapper {
    /**
     * 根据学号查找学生题目
     */
    List<Student_subject > selectOwnSubject(@Param("stuId") String stuId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_subject
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_subject
     *
     * @mbggenerated
     */
    int insert(Student_subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_subject
     *
     * @mbggenerated
     */
    int insertSelective(Student_subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_subject
     *
     * @mbggenerated
     */
    Student_subject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Student_subject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_subject
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Student_subject record);
}