package com.xyafu.gtms.dao;

import com.xyafu.gtms.entity.Teacher_topic;

import java.util.List;

public interface Teacher_topicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_topic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_topic
     *
     * @mbggenerated
     */
    int insert(Teacher_topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_topic
     *
     * @mbggenerated
     */
    int insertSelective(Teacher_topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_topic
     *
     * @mbggenerated
     */
    Teacher_topic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Teacher_topic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_topic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Teacher_topic record);

    /**
     * 按照教师id查找教师提交的选题
     */
    List selectMyTopic(String teaId);
}