package com.xyafu.gtms.dao;

import com.xyafu.gtms.entity.Teadirection;

import java.util.List;

public interface TeadirectionMapper {
    /**
     * 根据direction查找教师
     */
    List selectByDirection(String direction);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teadirection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teadirection
     *
     * @mbggenerated
     */
    int insert(Teadirection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teadirection
     *
     * @mbggenerated
     */
    int insertSelective(Teadirection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teadirection
     *
     * @mbggenerated
     */
    Teadirection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teadirection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Teadirection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teadirection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Teadirection record);
}