package com.xyafu.gtms.dao;

import com.xyafu.gtms.entity.Team_category;

public interface Team_categoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_category
     *
     * @mbggenerated
     */
    int insert(Team_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_category
     *
     * @mbggenerated
     */
    int insertSelective(Team_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_category
     *
     * @mbggenerated
     */
    Team_category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Team_category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Team_category record);
}