package com.xyafu.gtms.entity;

public class Level {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.level
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.sf
     *
     * @mbggenerated
     */
    private String sf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.level
     *
     * @return the value of level.level
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.level
     *
     * @param level the value for level.level
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.sf
     *
     * @return the value of level.sf
     *
     * @mbggenerated
     */
    public String getSf() {
        return sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.sf
     *
     * @param sf the value for level.sf
     *
     * @mbggenerated
     */
    public void setSf(String sf) {
        this.sf = sf == null ? null : sf.trim();
    }
}