package com.xyafu.gtms.entity;

public class Power {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.power
     *
     * @mbggenerated
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.onoff
     *
     * @mbggenerated
     */
    private Boolean onoff;
    private int funlevel;

    public int getFunlevel() {
        return funlevel;
    }

    public void setFunlevel(int funlevel) {
        this.funlevel = funlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.power
     *
     * @return the value of power.power
     *
     * @mbggenerated
     */
    public String getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.power
     *
     * @param power the value for power.power
     *
     * @mbggenerated
     */
    public void setPower(String power) {
        this.power = power == null ? null : power.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.onoff
     *
     * @return the value of power.onoff
     *
     * @mbggenerated
     */
    public Boolean getOnoff() {
        return onoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.onoff
     *
     * @param onoff the value for power.onoff
     *
     * @mbggenerated
     */
    public void setOnoff(Boolean onoff) {
        this.onoff = onoff;
    }

    @Override
    public String toString() {
        return "Power{" +
                "power='" + power + '\'' +
                ", onoff=" + onoff +
                ", funlevel=" + funlevel +
                '}';
    }
}