package com.xyafu.gtms.entity;


public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.Stu_id
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.Stu_pwd
     *
     * @mbggenerated
     */
    private String stuPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.Stu_name
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.Dept
     *
     * @mbggenerated
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.zhuanye
     *
     * @mbggenerated
     */
    private String zhuanye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.Stu_phone
     *
     * @mbggenerated
     */
    private String stuPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.Stu_timu
     *
     * @mbggenerated
     */
    private String stuTimu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.Stu_teacher
     *
     * @mbggenerated
     */
    private String stuTeacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.js.Stu_team
     *
     * @mbggenerated
     */
    private String stuTeam;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.Stu_id
     *
     * @return the value of student.js.Stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.Stu_id
     *
     * @param stuId the value for student.js.Stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.Stu_pwd
     *
     * @return the value of student.js.Stu_pwd
     *
     * @mbggenerated
     */
    public String getStuPwd() {
        return stuPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.Stu_pwd
     *
     * @param stuPwd the value for student.js.Stu_pwd
     *
     * @mbggenerated
     */
    public void setStuPwd(String stuPwd) {
        this.stuPwd = stuPwd == null ? null : stuPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.Stu_name
     *
     * @return the value of student.js.Stu_name
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.Stu_name
     *
     * @param stuName the value for student.js.Stu_name
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.Dept
     *
     * @return the value of student.js.Dept
     *
     * @mbggenerated
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.Dept
     *
     * @param dept the value for student.js.Dept
     *
     * @mbggenerated
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.zhuanye
     *
     * @return the value of student.js.zhuanye
     *
     * @mbggenerated
     */
    public String getZhuanye() {
        return zhuanye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.zhuanye
     *
     * @param zhuanye the value for student.js.zhuanye
     *
     * @mbggenerated
     */
    public void setZhuanye(String zhuanye) {
        this.zhuanye = zhuanye == null ? null : zhuanye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.Stu_phone
     *
     * @return the value of student.js.Stu_phone
     *
     * @mbggenerated
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.Stu_phone
     *
     * @param stuPhone the value for student.js.Stu_phone
     *
     * @mbggenerated
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.Stu_timu
     *
     * @return the value of student.js.Stu_timu
     *
     * @mbggenerated
     */
    public String getStuTimu() {
        return stuTimu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.Stu_timu
     *
     * @param stuTimu the value for student.js.Stu_timu
     *
     * @mbggenerated
     */
    public void setStuTimu(String stuTimu) {
        this.stuTimu = stuTimu == null ? null : stuTimu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.Stu_teacher
     *
     * @return the value of student.js.Stu_teacher
     *
     * @mbggenerated
     */
    public String getStuTeacher() {
        return stuTeacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.Stu_teacher
     *
     * @param stuTeacher the value for student.js.Stu_teacher
     *
     * @mbggenerated
     */
    public void setStuTeacher(String stuTeacher) {
        this.stuTeacher = stuTeacher == null ? null : stuTeacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.js.Stu_team
     *
     * @return the value of student.js.Stu_team
     *
     * @mbggenerated
     */
    public String getStuTeam() {
        return stuTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.js.Stu_team
     *
     * @param stuTeam the value for student.js.Stu_team
     *
     * @mbggenerated
     */
    public void setStuTeam(String stuTeam) {
        this.stuTeam = stuTeam == null ? null : stuTeam.trim();
    }

    /**
     * toString
     */
    @Override
    public String toString() {
        return "Student{" +
                "stuId='" + stuId + '\'' +
                ", stuPwd='" + stuPwd + '\'' +
                ", stuName='" + stuName + '\'' +
                ", dept='" + dept + '\'' +
                ", zhuanye='" + zhuanye + '\'' +
                ", stuPhone='" + stuPhone + '\'' +
                ", stuTimu='" + stuTimu + '\'' +
                ", stuTeacher='" + stuTeacher + '\'' +
                ", stuTeam='" + stuTeam + '\'' +
                '}';
    }
}