package com.xyafu.gtms.entity;

public class Teacher_topic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_topic.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_topic.topic
     *
     * @mbggenerated
     */
    private String topic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_topic.tea_id
     *
     * @mbggenerated
     */
    private String teaId;
    private String teaName;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_topic.Cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_topic.Y_N
     *
     * @mbggenerated
     */
    private Byte yN;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_topic.id
     *
     * @return the value of teacher_topic.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_topic.id
     *
     * @param id the value for teacher_topic.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_topic.topic
     *
     * @return the value of teacher_topic.topic
     *
     * @mbggenerated
     */
    public String getTopic() {
        return topic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_topic.topic
     *
     * @param topic the value for teacher_topic.topic
     *
     * @mbggenerated
     */
    public void setTopic(String topic) {
        this.topic = topic == null ? null : topic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_topic.tea_id
     *
     * @return the value of teacher_topic.tea_id
     *
     * @mbggenerated
     */
    public String getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_topic.tea_id
     *
     * @param teaId the value for teacher_topic.tea_id
     *
     * @mbggenerated
     */
    public void setTeaId(String teaId) {
        this.teaId = teaId == null ? null : teaId.trim();
    }
    public String getTeaName() {
        return teaName;
    }

    public void setTeaName(String teaName) {
        this.teaName = teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_topic.Cname
     *
     * @return the value of teacher_topic.Cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_topic.Cname
     *
     * @param cname the value for teacher_topic.Cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_topic.Y_N
     *
     * @return the value of teacher_topic.Y_N
     *
     * @mbggenerated
     */
    public Byte getyN() {
        return yN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_topic.Y_N
     *
     * @param yN the value for teacher_topic.Y_N
     *
     * @mbggenerated
     */
    public void setyN(Byte yN) {
        this.yN = yN;
    }
}