package com.xyafu.gtms.entity;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tea_id
     *
     * @mbggenerated
     */
    private String teaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tea_pwd
     *
     * @mbggenerated
     */
    private String teaPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tea_name
     *
     * @mbggenerated
     */
    private String teaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Dept
     *
     * @mbggenerated
     */
    private String dept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Ptitle
     *
     * @mbggenerated
     */
    private String ptitle;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tea_phone
     *
     * @mbggenerated
     */
    private String teaPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tea_team
     *
     * @mbggenerated
     */
    private String teaTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Plevel
     *
     * @mbggenerated
     */
    private String plevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tea_id
     *
     * @return the value of teacher.Tea_id
     *
     * @mbggenerated
     */
    public String getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tea_id
     *
     * @param teaId the value for teacher.Tea_id
     *
     * @mbggenerated
     */
    public void setTeaId(String teaId) {
        this.teaId = teaId == null ? null : teaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tea_pwd
     *
     * @return the value of teacher.Tea_pwd
     *
     * @mbggenerated
     */
    public String getTeaPwd() {
        return teaPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tea_pwd
     *
     * @param teaPwd the value for teacher.Tea_pwd
     *
     * @mbggenerated
     */
    public void setTeaPwd(String teaPwd) {
        this.teaPwd = teaPwd == null ? null : teaPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tea_name
     *
     * @return the value of teacher.Tea_name
     *
     * @mbggenerated
     */
    public String getTeaName() {
        return teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tea_name
     *
     * @param teaName the value for teacher.Tea_name
     *
     * @mbggenerated
     */
    public void setTeaName(String teaName) {
        this.teaName = teaName == null ? null : teaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Dept
     *
     * @return the value of teacher.Dept
     *
     * @mbggenerated
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Dept
     *
     * @param dept the value for teacher.Dept
     *
     * @mbggenerated
     */
    public void setDept(String dept) {
        this.dept = dept == null ? null : dept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Ptitle
     *
     * @return the value of teacher.Ptitle
     *
     * @mbggenerated
     */
    public String getPtitle() {
        return ptitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Ptitle
     *
     * @param ptitle the value for teacher.Ptitle
     *
     * @mbggenerated
     */
    public void setPtitle(String ptitle) {
        this.ptitle = ptitle == null ? null : ptitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Direction
     *
     * @return the value of teacher.Direction
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Direction
     *
     * @param direction the value for teacher.Direction
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tea_phone
     *
     * @return the value of teacher.Tea_phone
     *
     * @mbggenerated
     */
    public String getTeaPhone() {
        return teaPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tea_phone
     *
     * @param teaPhone the value for teacher.Tea_phone
     *
     * @mbggenerated
     */
    public void setTeaPhone(String teaPhone) {
        this.teaPhone = teaPhone == null ? null : teaPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tea_team
     *
     * @return the value of teacher.Tea_team
     *
     * @mbggenerated
     */
    public String getTeaTeam() {
        return teaTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tea_team
     *
     * @param teaTeam the value for teacher.Tea_team
     *
     * @mbggenerated
     */
    public void setTeaTeam(String teaTeam) {
        this.teaTeam = teaTeam == null ? null : teaTeam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Plevel
     *
     * @return the value of teacher.Plevel
     *
     * @mbggenerated
     */
    public String getPlevel() {
        return plevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Plevel
     *
     * @param plevel the value for teacher.Plevel
     *
     * @mbggenerated
     */
    public void setPlevel(String plevel) {
        this.plevel = plevel == null ? null : plevel.trim();
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "teaId='" + teaId + '\'' +
                ", teaPwd='" + teaPwd + '\'' +
                ", teaName='" + teaName + '\'' +
                ", dept='" + dept + '\'' +
                ", ptitle='" + ptitle + '\'' +
                ", teaPhone='" + teaPhone + '\'' +
                ", teaTeam='" + teaTeam + '\'' +
                ", plevel='" + plevel + '\'' +
                '}';
    }
}