package com.xyafu.gtms.entity;

public class Teadirection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teadirection.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teadirection.Tea_id
     *
     * @mbggenerated
     */
    private String teaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teadirection.Tea_name
     *
     * @mbggenerated
     */
    private String teaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teadirection.direction
     *
     * @mbggenerated
     */
    private String direction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teadirection.id
     *
     * @return the value of teadirection.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teadirection.id
     *
     * @param id the value for teadirection.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teadirection.Tea_id
     *
     * @return the value of teadirection.Tea_id
     *
     * @mbggenerated
     */
    public String getTeaId() {
        return teaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teadirection.Tea_id
     *
     * @param teaId the value for teadirection.Tea_id
     *
     * @mbggenerated
     */
    public void setTeaId(String teaId) {
        this.teaId = teaId == null ? null : teaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teadirection.Tea_name
     *
     * @return the value of teadirection.Tea_name
     *
     * @mbggenerated
     */
    public String getTeaName() {
        return teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teadirection.Tea_name
     *
     * @param teaName the value for teadirection.Tea_name
     *
     * @mbggenerated
     */
    public void setTeaName(String teaName) {
        this.teaName = teaName == null ? null : teaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teadirection.direction
     *
     * @return the value of teadirection.direction
     *
     * @mbggenerated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teadirection.direction
     *
     * @param direction the value for teadirection.direction
     *
     * @mbggenerated
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    @Override
    public String toString() {
        return "Teadirection{" +
                "id=" + id +
                ", teaId='" + teaId + '\'' +
                ", teaName='" + teaName + '\'' +
                ", direction='" + direction + '\'' +
                '}';
    }
}