package com.xyafu.gtms.entity;

public class Team {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Tname
     *
     * @mbggenerated
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Nteacher
     *
     * @mbggenerated
     */
    private String nteacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Nstudent
     *
     * @mbggenerated
     */
    private String nstudent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Tnumber
     *
     * @mbggenerated
     */
    private String tnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.Snumber
     *
     * @mbggenerated
     */
    private String snumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.id
     *
     * @return the value of team.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.id
     *
     * @param id the value for team.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Tname
     *
     * @return the value of team.Tname
     *
     * @mbggenerated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Tname
     *
     * @param tname the value for team.Tname
     *
     * @mbggenerated
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Cname
     *
     * @return the value of team.Cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Cname
     *
     * @param cname the value for team.Cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Nteacher
     *
     * @return the value of team.Nteacher
     *
     * @mbggenerated
     */
    public String getNteacher() {
        return nteacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Nteacher
     *
     * @param nteacher the value for team.Nteacher
     *
     * @mbggenerated
     */
    public void setNteacher(String nteacher) {
        this.nteacher = nteacher == null ? null : nteacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Nstudent
     *
     * @return the value of team.Nstudent
     *
     * @mbggenerated
     */
    public String getNstudent() {
        return nstudent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Nstudent
     *
     * @param nstudent the value for team.Nstudent
     *
     * @mbggenerated
     */
    public void setNstudent(String nstudent) {
        this.nstudent = nstudent == null ? null : nstudent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Tnumber
     *
     * @return the value of team.Tnumber
     *
     * @mbggenerated
     */
    public String getTnumber() {
        return tnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Tnumber
     *
     * @param tnumber the value for team.Tnumber
     *
     * @mbggenerated
     */
    public void setTnumber(String tnumber) {
        this.tnumber = tnumber == null ? null : tnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.Snumber
     *
     * @return the value of team.Snumber
     *
     * @mbggenerated
     */
    public String getSnumber() {
        return snumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.Snumber
     *
     * @param snumber the value for team.Snumber
     *
     * @mbggenerated
     */
    public void setSnumber(String snumber) {
        this.snumber = snumber == null ? null : snumber.trim();
    }
}